version: '3.8'

services:
  prairie-app:
    container_name: prairie
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - reseau_virtuel_pour_maggie

  rtsp-to-web:
    image: ghcr.io/deepch/rtsptoweb:latest
    volumes:
      - ./tsconfig.json:/config/tsconfig.json:ro
    ports:
      - '8083:8083'
      - '5541:5541' 
    container_name: rtsp-to-web
    networks:
      - reseau_virtuel_pour_maggie

networks:
  reseau_virtuel_pour_maggie:
    driver: bridge  # Defines the network
